// galaxyui/src/app/authors-react/react-components/page-header.tsx
import * as React from 'react';
import { Link } from './link';
import './page-header.less';

interface IPageHeaderProp {
    headerIcon: string;
    headerTitle: string;
}

export class PageHeader extends React.Component<IPageHeaderProp, {}> {
    render() {
        const title_list = this.props.headerTitle.split(';');
        const breadcrumbs = [];

        if (this.props.headerIcon) {
            breadcrumbs.push(
                <li key={-3}>
                    <span className={this.props.headerIcon} />
                </li>,
            );
        }

        if (title_list.length > 1) {
            breadcrumbs.push(
                <li key={-2} className='show-on-mobile'>
                    <span className='fa fa-angle-double-right' />
                </li>,
            );
        }

        title_list.forEach((item: string, idx: number) => {
            if (idx % 2) {
                const name = title_list[idx - 1];
                const path = item;
                breadcrumbs.push(
                    <li key={idx} className='hide-on-mobile'>
                        <Link to={path}>{name}</Link>
                        <span className='separator'>
                            <span className='fa fa-angle-right' />
                        </span>
                    </li>,
                );
            }
            if (idx === title_list.length - 1) {
                const name = item;
                breadcrumbs.push(<li key={'last'}>{name}</li>);
            }
        });

        return (
            <div className='page-header-react-wrapper'>
                <div className='page-header'>
                    <ul className='page-header-list'>{breadcrumbs}</ul>
                </div>
            </div>
        );
    }
}

// galaxyui/src/app/shared/components/page-header/page-header.component.ts
import { Component, Input, OnInit } from '@angular/core';

class Title {
    name: string;
    path: string;
}

@Component({
    selector: 'app-page-header',
    templateUrl: './page-header.component.html',
    styleUrls: ['./page-header.component.less'],
})
export class PageHeaderComponent implements OnInit {
    // Used to track which component is being loaded
    componentName = 'PageHeaderComponent';

    _headerTitle: Title[];
    _headerIcon: string;

    @Input()
    set headerTitle(headerTitle: string) {
        // Set headerTitle to a string. For sub pages, where you want a breadcrumb trail,
        // pass a list of page names and paths separated by ';'. For example:
        // 'page_name;/path;page_name;/path/foo;page_name'.

        const title_list = headerTitle.split(';');
        this._headerTitle = [];
        title_list.forEach((item: string, idx: number) => {
            if (idx % 2) {
                const title = new Title();
                title.name = title_list[idx - 1];
                title.path = item;
                this._headerTitle.push(title);
            } else if (idx === title_list.length - 1) {
                const title = new Title();
                title.name = item;
                this._headerTitle.push(title);
            }
        });
    }

    @Input()
    set headerIcon(icon: string) {
        this._headerIcon = icon;
    }

    constructor() {}

    ngOnInit() {}
}

<div class="page-header">
    <ul class="page-header-list">
        <li><span *ngIf="_headerIcon" class="{{ _headerIcon }}"></span></li>
        <li *ngIf="_headerTitle.length > 1" class="show-on-mobile"><span class="fa fa-angle-double-right"></span></li>
        <li *ngFor="let title of _headerTitle; index as i; let last=last" [ngClass]="{'hide-on-mobile': !last}">
            <a appLogEvent [routerLink]="[title.path]" *ngIf="title.path" [innerHTML]="title.name"></a>
            <span *ngIf="i < _headerTitle.length - 1" class="separator"><span class="fa fa-angle-right"></span></span>
            <span *ngIf="!title.path" [innerHTML]="title.name"></span>
        </li>
    </ul>
</div>
