// galaxyui/src/app/shared/components/page-loading/page-loading.component.ts
import {
    Component,
    Input,
    OnInit
} from '@angular/core';

@Component({
    selector: 'app-page-loading',
    templateUrl: './page-loading.component.html',
    styleUrls: ['./page-loading.component.less']
})
export class PageLoadingComponent implements OnInit {
    @Input() loading: boolean;

    constructor() { }

    ngOnInit() {}
}

<div class="page-loader" [ngClass]="{'hide-content': !loading}">
    <div class="page-loading-inner"><span class="fa fa-spinner fa-spin fa-5x"></span></div>
</div>

// galaxyui/src/app/react/components/page-loading.tsx
import * as React from 'react';

interface IProps {
    loading: boolean;
}

export class PageLoading extends React.Component<IProps, {}> {
    render() {
        // [ngClass]="{'hide-content': !loading}"
        return (
            <div className='page-loading-wrapper'>
                <div
                    className={
                        'page-loader' +
                        (this.props.loading ? '' : ' hide-content')
                    }
                >
                    <div className='page-loading-inner'>
                        <span className='fa fa-spinner fa-spin fa-5x' />
                    </div>
                </div>
            </div>
        );
    }
}
